# Generated by Django 2.0.5 on 2018-06-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name': 'Tipo de actividad', 'verbose_name_plural': 'Tipo de actividades'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_dolar',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_peso',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='precio_dolar',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='precio_peso',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
