# Generated by Django 2.0.5 on 2018-07-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180627_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='hectareas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaña',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: Soja Primavera 2018', max_length=50, verbose_name='Nombre de la campaña'),
        ),
    ]
