# Generated by Django 2.0.5 on 2018-07-04 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180704_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=6)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_inicial', models.BooleanField(default=False, help_text='Calcular stock a partir de esta cantidad')),
                ('precio_peso', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_dolar', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Actividad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: compra, venta', max_length=50)),
                ('aumenta', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.TipoMovimiento'),
        ),
    ]
