# Generated by Django 2.1 on 2018-08-15 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180704_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
