# Generated by Django 2.0.2 on 2018-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20180815_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='letra_comp',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('M', 'M'), ('E', 'E'), ('X', 'X')], default='X', help_text='Letra del comprobante', max_length=1),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nro_comp',
            field=models.IntegerField(default='089'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pto_venta',
            field=models.IntegerField(default='0001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_comp',
            field=models.CharField(choices=[('001', 'Factura A'), ('004', 'Recibos A'), ('006', 'Factura B'), ('009', 'Recibos B'), ('011', 'Factura C'), ('015', 'Recibos C'), ('017', 'Liq.Serv.Publ.A'), ('018', 'Liq.Serv.Publ.B'), ('033', 'Liq.Prim.de Granos'), ('089', 'Resumen de datos')], default='OPC_TC.001', help_text='Tipo de comprobante', max_length=3),
        ),
    ]
