# Generated by Django 2.0.2 on 2018-10-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20181015_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='letra_comp',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('M', 'M'), ('E', 'E'), ('X', 'X')], default='X', max_length=1, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='nro_comp',
            field=models.IntegerField(verbose_name='Número de comprobante'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='pto_venta',
            field=models.IntegerField(verbose_name='Punto de venta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_comp',
            field=models.CharField(choices=[('001', 'Factura A'), ('004', 'Recibos A'), ('006', 'Factura B'), ('009', 'Recibos B'), ('011', 'Factura C'), ('015', 'Recibos C'), ('017', 'Liq.Serv.Publ.A'), ('018', 'Liq.Serv.Publ.B'), ('033', 'Liq.Prim.de Granos'), ('089', 'Resumen de datos')], default='OPC_TC.089', max_length=3, verbose_name='Tipo de comprobante'),
        ),
    ]
