# Generated by Django 2.0.2 on 2018-10-31 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20181024_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_cosechable',
            field=models.BooleanField(default=False, help_text='Es resultado del producido de una campaña ?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_dolar',
            field=models.DecimalField(decimal_places=3, help_text='Precio en dólares según la cotización del día.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_peso',
            field=models.DecimalField(decimal_places=3, help_text='Precio neto unitario según unidad de medida.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(help_text='Ingresar nombre abreviado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.UnidadMedida'),
        ),
    ]
